### ISSUE TITLE
Particular DOI does not resolve

### ISSUE THREAD

**Issue by bgo-eiu** [rdmpage/bhl-wikidata#10]
See this DOI:

https://doi.org/10.1515/9781501505140-007

It appears to be valid, but when entered into the tool a server error results. I have not seen this occur with other DOIs so far.

**Comment by bgo-eiu** [comment]
The volume this is published in has its own DOI, as do each of the other chapters/articles. They all seem to have the same issue. Possibly of note is that these DOIs are derived from the ISBN of the volume.

**Comment by rdmpage** [comment]
@bgo-eiu Thanks for pointing this out, the code to handle ISBNs was broken. I've fixed it. If you add the book first (e.g., [Q115868940](https://www.wikidata.org/wiki/Q115868940)) then the chapters will be automatically linked to that book.
