### ISSUE TITLE
Adding cites work statements when the DOI has already been added to Wikidata 

### ISSUE THREAD

**Issue by HelsKRW** [rdmpage/bhl-wikidata#12]
Someone has just pointed me to this tool and it's amazing - thank you! I had been looking for a way to easily gather metadata for 'cites work' statements and hadn't achieved it.   I am really keen to return to DOIs from our University Press journals where I've already uploaded metadata to Wikidata, but could now potentialy add cites work statements - for example, https://www.wikidata.org/wiki/Q115695284 .  Is there any way to do this via your tool?  I am getting a message that says the DOI already exists in Wikidata - is there any way to bypass this in order to obtain and add the references data? 
Thank you again 
Best wishes
Helen

**Comment by rdmpage** [comment]
Hi @HelsKRW Glad you like the tool, it's very much a quick and dirty hack.

I have code for adding citations via CrossRef metadata - sadly limited to those citations which have DOIs, which means a lot of citations are missed, but at least it is a start. In an ideal world we'd also be able to try and match citations that don't have DOIs, but that's perhaps for another day.

 I wonder if the best approach would be to have that as a separate tool where you paste in a DOI or a Wikidata id, and if that item exists in Wikidata then the tool attempts to add/update citations. Would that be useful?

**Comment by HelsKRW** [comment]
Hi @rdmpage 
Thanks for responding so quickly - that's really kind of you. 
It's definitely a great start to be able to add the citations with a DOI - that's much more than I've been able to do up to this point - thank you. 
It would be wonderful to have something separate where you could add/update citations if the item is already in Wikidata - I would definitely try running some of our content through that to see if I could add citations that aren't currently included in the Wikidata items I've created. 
Best wishes
Helen

**Comment by rdmpage** [comment]
Hi @HelsKRW 
OK, I've added a tool for finding cited works, see https://bhl2wiki.herokuapp.com/cites.php 

This is very crude, but you may find it useful. It is designed to find citation links between works with DOIs where those DOIs have items in Wikidata. Put another way, if the DOI you enter isn't in Wikidata, the tool won't work. Likewise, a work might cite another work with a DOI, but if the cited work isn't in Wikidata, the tool won't return that link.

One thing I find useful is to look at the article I want to use the tool on, and add any missing works to Wikidata so that I get more links. This could eventually be automated, but pretty quickly we'd end up crawling the entire academic citation graph 😨 

Let me know if this is helpful.

Rod

**Comment by HelsKRW** [comment]
Hi @rdmpage 
Thanks so much for creating this Rod - I've just used it to add cites works statements for a journal issue on our university press and it's working really well.  I think this could also be really useful on a thesis dataset I've been working on so am about to experiment with that too.  It's always exciting to be able to make these new connections - where the data's already in Wikidata.  I like the top tip to add any missing works before using the tool if necessary.  
A huge thanks, again, for using your technical skills to create something that's really useful for our work! 
Best wishes
Helen

**Comment by rdmpage** [comment]
@HelsKRW Glad it's useful. 

Another tool I've built is "ALEC" which is a way to browse Wikidata with a heavy emphasis on publications, people, and species (I'm a biologist). For example, http://alec-demo.herokuapp.com/Q115695282 shows an item you've edited. ALEC lists articles that cite, are cited by, and are related by co-citation. For example, http://alec-demo.herokuapp.com/Q24670012 (a work cited by Q115695282) has a large number of related articles, which is sometimes nice way to discover interesting articles. I also use ALEC to discover gaps in coverage as I add articles and journals to Wikidata.

I'm guessing you've also seen Scholia? I include links to the Scholia project on ALEC pages for publications and people.

**Comment by HelsKRW** [comment]
thanks @rdmpage ALEC looks great - I will explore further.  It's really interesting to see some new tools - or new to me at least!
I've been adding our data from JIED and LSEPPR to Wikidata and then looking at what we can see in Scholia.  
https://scholia.toolforge.org/venue/Q96715673 and https://scholia.toolforge.org/venue/Q97011661
We have some articles that need subjects added and a lot where author name strings need to be matched to Qids/Qids created via Author Disambiguator... just waiting for time to train a couple of my team on that at the moment.  Thanks again!  
Helen

**Comment by rdmpage** [comment]
I have a super crude tool for converting author names to authors, e.g. https://ozymandias-demo.herokuapp.com/wikidata-match.php?q=Jonathan+Hopkin

I think I built this at a time when Author Disambiguator was offline and I needed a quick fix. This tool just matches names, only matches to one Wikidata author (so doesn’t handle cases where > 1 person with same name is in Wikidata), and mostly relies on user figuring out which names are the same (e.g., using clues such as journal names). In my field author names are often unique and it works pretty well, but it feels like getting in a car with no seat belts. Use at your own risk.


Regards, Rod

**Comment by HelsKRW** [comment]
Hi @rdmpage 
We're frequently needing to use Author Disamiguator to create new Qids as well, but it's really good to know about this as an AD back up if we're just matching to update name strings to authors.  Thanks for sharing it - that's really kind of you 
Helen
