### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by dpriskorn** [rdmpage/bhl-wikidata#7]
https://bhl2wiki.herokuapp.com/?ids=10.4067%2FS0034-98872000000600002%0D%0A&add=
![bild](https://user-images.githubusercontent.com/68460690/200526590-71ff67ba-2dfe-4c07-8e54-15e9cbbf2399.png)

see https://www.researchgate.net/publication/240114817_Creencias_actitudes_y_conocimientos_en_educacion_sexual for DOI

**Comment by dpriskorn** [comment]
![bild](https://user-images.githubusercontent.com/68460690/200527200-5ce42ddc-8eba-46d7-aab8-7bd271416382.png)
sourcemd generated the statements just fine it seems

**Comment by rdmpage** [comment]
@dpriskorn Not sure what happened here, the logs simply say it timed out.
