### ISSUE TITLE
500 internal server error and blank page

### ISSUE THREAD

**Issue by dpriskorn** [rdmpage/bhl-wikidata#9]
![image](https://user-images.githubusercontent.com/68460690/201120015-97c79c1e-371f-48eb-91ad-a61dfc00e3dd.png)
https://bhl2wiki.herokuapp.com/?ids=10.1007/978-3-319-23597-4_52

**Comment by dpriskorn** [comment]
![image](https://user-images.githubusercontent.com/68460690/201120193-a747d06a-260a-4268-83c9-24ed18aa9e72.png)
sourcemd succeed

**Comment by rdmpage** [comment]
@dpriskorn  Sadly I can't replicate this now because the DOI exists in Wikidata :wink:

**Comment by dpriskorn** [comment]
Oh, yeah, sorry about that. I'll reopen when I find another example for you to reproduce
